### ISSUE TITLE
Passport User Listing Error

### ISSUE THREAD

**Issue by miguemely** [vatesfr/xo-server-auth-google#1]
When a user logs in utilizing the Google authentication plugin and does not have Google+ set up, the listing for the user is blank and does not pull a email.

**Comment by olivierlambert** [comment]
@miguemely do you know what we can fetch otherwise? Is it "normal" to haven't any email when the user haven't a G+ account?

**Comment by cl0s** [comment]
Can you fetch anything else?  Having it blank makes it impossible to know which id matches which user, so you can't setup ACLs or assign permissions.  Also when the google+ is setup i grabs the name, not the email.

**Comment by olivierlambert** [comment]
@julien-f we'll probably need to display in debug all the available fields to find the right one.

**Comment by miguemely** [comment]
@olivierlambert I don't know specifically what the API can give you by calls, but it 'should' give you the email from it.

**Comment by miguemely** [comment]
I would have to look deeper into it.

**Comment by miguemely** [comment]
Oh I see whats going on. Your using the Google Plus API for it. 
(Source:https://developers.google.com/+/web/signin/#set_up_google_sign-in_for_google)

I'm trying to see if Google Identity could be used instead, since more information can be pulled from it.

**Comment by miguemely** [comment]
@vatesfr Look at #2

**Comment by julien-f** [comment]
@miguemely Thank you very much for your work, you don't have the time to do everything :p
